language: julia

os:
  - linux

julia:
  - release
  
notifications:
  email: false
 
before_install:
   - julia -e 'Pkg.add("MAT");'
   - julia -e 'Pkg.clone("https://github.com/lruthotto/KrylovMethods.jl","KrylovMethods"); Pkg.build("KrylovMethods");'
   - julia -e 'Pkg.clone("https://github.com/JuliaInv/jInv.jl","jInv"); Pkg.build("jInv");'
   - julia -e 'Pkg.clone("https://github.com/JuliaInv/FactoredEikonalFastMarching.jl","FactoredEikonalFastMarching"); Pkg.build("FactoredEikonalFastMarching");'
   - julia -e 'Pkg.clone("https://github.com/JuliaInv/EikonalInv.jl","EikonalInv"); Pkg.build("EikonalInv");'
   - julia -e 'Pkg.clone("https://github.com/JuliaInv/Multigrid.jl","Multigrid"); Pkg.build("Multigrid");'
   - julia -e 'Pkg.clone("https://github.com/JuliaInv/ForwardHelmholtz.jl","ForwardHelmholtz"); Pkg.build("ForwardHelmholtz");'
   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("FWI"); Pkg.test("FWI"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("FWI")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
